env = Environment()

env['APP_TARGET'] = 'Fluid2DCamApp'
env['APP_SOURCES'] = ['Fluid2DCamApp.cpp']

env = SConscript('../../../scons/SConscript', exports = 'env')
env = SConscript('../../../../../blocks/Cinder-OpenCV/scons/SConscript', exports = 'env')
SConscript('../../../../../scons/SConscript', exports = 'env')

