env = Environment()

env['APP_TARGET'] = 'Fluid2DRGBApp'
env['APP_SOURCES'] = ['Fluid2DRGBApp.cpp']

env = SConscript('../../../scons/SConscript', exports = 'env')
SConscript('../../../../../scons/SConscript', exports = 'env')

