env = Environment()

env['APP_TARGET'] = 'Fluid2DBasicApp'
env['APP_SOURCES'] = ['Fluid2DBasicApp.cpp']

env = SConscript('../../../scons/SConscript', exports = 'env')
SConscript('../../../../../scons/SConscript', exports = 'env')

