env = Environment()

env['APP_TARGET'] = 'Fluid2DParticlesApp'
env['APP_SOURCES'] = ['Fluid2DParticlesApp.cpp', 'Particles.cpp']

env = SConscript('../../../scons/SConscript', exports = 'env')
SConscript('../../../../../scons/SConscript', exports = 'env')

